language: c

matrix:
  include:

    - name: "Ubuntu 16.04 LTS (Xenial Xerus) GCC 5" 
      os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - libpcap-dev
            - expect
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++ && CC_FLAGS=-march=native"

    - name: "Ubuntu 16.04 LTS (Xenial Xerus) GCC 6" 
      os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libpcap-dev
            - expect
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6 && CC_FLAGS=-march=native"

    - name: "Ubuntu 16.04 LTS (Xenial Xerus) GCC 7" 
      os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libpcap-dev
            - expect
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && CC_FLAGS=-march=native"

    - name: "Ubuntu 16.04 LTS (Xenial Xerus) GCC 8" 
      os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - libpcap-dev
            - expect
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8 && CC_FLAGS=-march=native"

    - name: "Ubuntu 16.04 LTS (Xenial Xerus) GCC 9" 
      os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - libpcap-dev
            - expect
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9 && CC_FLAGS=-march=native"

    - name: "Ubuntu 18.04 LTS (Bionic Beaver) GCC 7" 
      os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - libpcap-dev
            - expect
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++ && CC_FLAGS=-march=native"

    - name: "Ubuntu 18.04 LTS (Bionic Beaver) GCC 8" 
      os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - libpcap-dev
            - expect
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8 && CC_FLAGS=-march=native"

    - name: "Ubuntu 18.04 LTS (Bionic Beaver) Clang 4" 
      os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - llvm-toolchain-bionic-4.0
          packages:
            - clang-4.0
            - libpcap-dev
            - expect
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0 && CC_FLAGS=-march=native"

    - name: "Ubuntu 18.04 LTS (Bionic Beaver) Clang 5" 
      os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - llvm-toolchain-bionic-5.0
          packages:
            - clang-5.0
            - libpcap-dev
            - expect
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0 && CC_FLAGS=-march=native"

    - name: "Ubuntu 18.04 LTS (Bionic Beaver) Clang 6" 
      os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - llvm-toolchain-bionic-6.0
          packages:
            - clang-6.0
            - libpcap-dev
            - expect
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0 && CC_FLAGS=-march=native"

    - name: "Ubuntu 18.04 LTS (Bionic Beaver) Clang 7" 
      os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - llvm-toolchain-bionic-7
          packages:
            - clang-7
            - libpcap-dev
            - expect
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7 && CC_FLAGS=-march=native"

    - name: "Ubuntu 18.04 LTS (Bionic Beaver) Clang 8" 
      os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - llvm-toolchain-bionic-8
          packages:
            - clang-8
            - libpcap-dev
            - expect
      env:
        - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8 && CC_FLAGS=-march=native"

    - name: "Ubuntu 18.04 LTS (Bionic Beaver) Clang 9"
      os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - llvm-toolchain-bionic-9
          packages:
            - clang-9
            - libpcap-dev
            - expect
      env:
        - MATRIX_EVAL="CC=clang-9 && CXX=clang++-9 && CC_FLAGS=-march=native"

    - name: "Ubuntu 18.04 LTS (Bionic Beaver) Clang 10"
      os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - llvm-toolchain-bionic-10
          packages:
            - clang-10
            - libpcap-dev
            - expect
      env:
        - MATRIX_EVAL="CC=clang-10 && CXX=clang++-10 && CC_FLAGS=-march=native"

    - name: "Ubuntu 18.04 LTS (Bionic Beaver) GCC 7 @ MIPS64"
      os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - gcc-mips64-linux-gnuabi64
            - libc-dev-mips64-cross
            - qemu-user-static
            - expect
      env:
        - MATRIX_EVAL="CC=mips64-linux-gnuabi64-gcc && CXX=mips64-linux-gnuabi64-g++"
      before_install:
        - sudo mkdir "/usr/mips64-linux-gnuabi64/etc"
        - sudo touch "/usr/mips64-linux-gnuabi64/etc/ld.so.cache"
        - sudo mkdir "/etc/qemu-binfmt"
        - sudo ln -sf "/usr/mips64-linux-gnuabi64" "/etc/qemu-binfmt/mips64"
        - eval "${MATRIX_EVAL}"

before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  - mkdir platforms/posix/build
  - cmake --version
  - cmake -DCMAKE_CC_FLAGS="-Werror ${CC_FLAGS}" -Bplatforms/posix/build -Hplatforms/posix

script:
  - make -C platforms/posix/build
  - cd platforms/posix/build
  - ctest -V
