#define USIPY_HF_generic            0
#define USIPY_HF_ALLOW              1
#define USIPY_HF_ALSO               2
#define USIPY_HF_AUTHORIZATION      3
#define USIPY_HF_CCDIVERSION        4
#define USIPY_HF_CSEQ               5
#define USIPY_HF_CALLID             6
#define USIPY_HF_CONTACT            7
#define USIPY_HF_CONTENTLENGTH      8
#define USIPY_HF_CONTENTTYPE        9
#define USIPY_HF_DIVERSION          10
#define USIPY_HF_EXPIRES            11
#define USIPY_HF_FROM               12
#define USIPY_HF_MAXFORWARDS        13
#define USIPY_HF_PASSERTEDIDENTITY  14
#define USIPY_HF_PROXYAUTHENTICATE  15
#define USIPY_HF_PROXYAUTHORIZATION 16
#define USIPY_HF_RACK               17
#define USIPY_HF_RSEQ               18
#define USIPY_HF_REASON             19
#define USIPY_HF_RECORDROUTE        20
#define USIPY_HF_REFERTO            21
#define USIPY_HF_REFERREDBY         22
#define USIPY_HF_REPLACES           23
#define USIPY_HF_ROUTE              24
#define USIPY_HF_SERVER             25
#define USIPY_HF_SUPPORTED          26
#define USIPY_HF_TO                 27
#define USIPY_HF_USERAGENT          28
#define USIPY_HF_VIA                29
#define USIPY_HF_WWWAUTHENTICATE    30
#define USIPY_HF_WARNING            31
#define USIPY_HF_CALLID_c           32
#define USIPY_HF_CONTACT_c          33
#define USIPY_HF_CONTENTLENGTH_c    34
#define USIPY_HF_CONTENTTYPE_c      35
#define USIPY_HF_FROM_c             36
#define USIPY_HF_REFERTO_c          37
#define USIPY_HF_TO_c               38
#define USIPY_HF_VIA_c              39
#define USIPY_HF_max                39
